services:
  mongodb:
    image: mongo:6.0.3
    container_name: mongodb
    ports:
      - "27017:27017"
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
